#!/usr/bin/env bash
set -e

repo="yanskun/gh-release-up"
exe="gh-release-up-v1.1.0"
extensionPath="$(dirname "$0")"

if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
  mkdir -p "${extensionPath}/bin"
  rm -f "${extensionPath}/bin/gh-default-branch-"*
  gh release -R"${repo}" download "${tag}" -p "${exe}" --dir="${extensionPath}/bin"
  chmod +x "${extensionPath}/bin/${exe}"
fi

tag=$(exec "${extensionPath}/bin/${exe}" "$@")

if [ $(echo "${tag}" | wc -l) -gt 1 ]; then
  echo "${tag}"
  exit 1
fi

echo -e "New tag is: $(tput bold)${tag}"
echo -n "$(tput sgr0)Are you sure? [Y/n]:"
read ANS
case $ANS in
  "" | [yY]* )
    exec gh release create "${tag}" --title "${tag}"
    ;;
  * )
    echo "Canceled"
    exit 1
    ;;
esac
