#!/usr/bin/env bash
set -e

repo="yanskun/gh-release-up"
exe="gh-release-up-v1.0.1"
extensionPath="$(dirname "$0")"

if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
  mkdir -p "${extensionPath}/bin"
  rm -f "${extensionPath}/bin/gh-default-branch-"*
  gh release -R"${repo}" download "${tag}" -p "${exe}" --dir="${extensionPath}/bin"
  chmod +x "${extensionPath}/bin/${exe}"
fi

tag=$(exec "${extensionPath}/bin/${exe}" "$@")

echo -e "New tag is: ${tag}\nAre you sure? [Y/n]:"
read ANS
case $ANS in
  "" | [yY]* )
    exec gh release create "${tag}" --title "${tag}"
    ;;
  * )
    echo "Canceled"
    exit 1
    ;;
esac
